### ISSUE TITLE
零基础免费搭建个人博客-hexo+github | Hifor

### ISSUE THREAD

**Issue by hifor** [hifor/github-pages-comment#9]
http://hifor.net/2015/07/01/%E9%9B%B6%E5%9F%BA%E7%A1%80%E5%85%8D%E8%B4%B9%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2-hexo-github/

**Comment by hifor** [comment]
主题的配置文件:
```yaml
#评论插件
#gitment
gitment:
  owner: hifor
  repo: github-pages-comment
  client_id: 4ee****a32c
  client_secret: f9***016931d3
```

模板文件:
```html
<% if (!index && post.comments && theme.gitment){ %>
<section id="comments"></section>
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
<script>
    var labels = "blog,gitment";
    labels = labels.split(",");
    var gitment = new Gitment({
        id: window.location.pathname,
        owner: '<%- theme.gitment.owner %>',
        repo: '<%- theme.gitment.repo %>',
        oauth: {
            client_id: '<%- theme.gitment.client_id %>',
            client_secret: '<%- theme.gitment.client_secret %>'
        },
        labels: labels
    })
    gitment.render('comments');
</script>
<% } %>
```
